server:
  port: 8080
spring:
  application:
    name: reggie_take_out
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 0929
#  mvc:
#    static-path-pattern: /static/**

mybatis-plus:
  configuration:

    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: assign_id
reggie:
  path: E:\Workspace\Java\exercise\reggie\reggie_take_out\img\